#You've been informed about a new Ansible Collection named networking_tools under the namespace company_xyz. This collection contains specialized modules for network automation. You need to write a playbook that installs this collection and then uses a custom module named configure_vlan from it to set up VLAN 10 with the name Admin_VLAN.


#Complete the playbook located at /home/bob/playbooks/playbook.yml to correctly install the networking_tools collection and utilize the configure_vlan module. You just need to fill the placeholders in this playbook.+

---
- hosts: localhost
  tasks:
    - name: Install the networking_tools collection
      ansible.builtin.ansible_galaxy_collection:
        name: company_xyz.networking_tools  
        source: https://galaxy.ansible.com

- hosts: switches
  collections:
    - company_xyz.networking_tools
  tasks:
    - name: Configure VLAN 10
      configure_vlan:
        vlan_id: 10
        vlan_name: Admin_VLAN
