
#Navigate to /home/bob/playbooks/inventory/ directory. A report template named inventory.csv.j2 is given under the templates directory.
#
#Update the template to print the requested details of all hosts defined in /home/bob/playbooks/inventory/inventory file. Further update /home/bob/playbooks/inventory/generate-inventory.yml playbook to generate the report and place it on the student-node node at /tmp/inventory.csv

#
#Use below variables from the gathered facts for each host.
#
#
#ansible_architecture
#ansible_distribution_version
#ansible_memtotal_mb
#ansible_processor_cores
#ansible_processor_count



#for template update


hostname, architecture, distribution_version, mem_total_mb, processor_cores, processor_count
{% for host in groups['web'] %}
{{ host }}, {{ hostvars[host]['ansible_architecture'] }}, {{ hostvars[host]['ansible_distribution_version'] }}, {{ hostvars[host]['ansible_memtotal_mb'] }}, {{ hostvars[host]['ansible_processor_cores'] }}, {{ hostvars[host]['ansible_processor_count'] }}
{% endfor %}



#for generate-inventory.yml

- hosts: all
  tasks:
  - setup:

- hosts: localhost
  tasks:
    - template:
        src: inventory.csv.j2
        dest: /tmp/inventory.csv
      run_once: yes
